platforms: [linux/amd64, linux/arm64]
context: images/golang
tag: golang
versions:
  "1.25-alpine3.22":
    dockerfile: |
      FROM golang:1.25-alpine3.22
  "1.25-alpine3.23":
    dockerfile: |
      FROM golang:1.25-alpine3.23
  "1.26-alpine3.22":
    dockerfile: |
      FROM golang:1.26-alpine3.22
  "1.26-alpine3.23":
    dockerfile: |
      FROM golang:1.26-alpine3.23
