images:
  alpine:
    platforms: [linux/amd64, linux/arm64]
    context: images/alpine
    tag: alpine
    version: 3.21
    dockerfile: |
      FROM alpine:3.21

  goappbuilder:
    platforms: [linux/amd64, linux/arm64]
    context: images/goappbuilder
    tag: goapp-builder
    version: 1.23.8-alpine3.21
    dockerfile: images/goappbuilder/Dockerfile

  # olmocr: # Out of space error
  #   platforms: [linux/amd64, linux/arm64]
  #   context: images/olmocr
  #   tag: olmocr
  #   version: cuda124-ubuntu2204
  #   dockerfile: images/olmocr/Dockerfile

  ray:
    platforms: [linux/amd64]
    context: images/ray
    tag: ray
    version: 2.44.1-py311-numpy2x
    dockerfile: images/ray/Dockerfile

  rayarm64:
    platforms: [linux/arm64]
    context: images/rayarm64
    tag: ray
    version: 2.44.1-py311-numpy2x-aarch64
    dockerfile: images/rayarm64/Dockerfile

  node:
    platforms: [linux/amd64, linux/arm64]
    context: images/node
    tag: node
    version: 24-alpine3.21
    dockerfile: |
      FROM node:24-alpine3.21

  nginx:
    platforms: [linux/amd64, linux/arm64]
    context: images/nginx
    tag: nginx
    version: 1.27-alpine3.21
    dockerfile: |
      FROM nginx:1.27-alpine3.21

  redis:
    platforms: [linux/amd64, linux/arm64]
    context: images/redis
    tag: redis
    version: 8-alpine3.21
    dockerfile: |
      FROM docker.io/redis:8-alpine3.21

  postgres:
    platforms: [linux/amd64, linux/arm64]
    context: images/postgres
    tag: postgres
    version: 17.5-alpine3.21
    dockerfile: |
      FROM docker.io/postgres:17.5-alpine3.21

  pgvector:
    platforms: [linux/amd64, linux/arm64]
    context: images/pgvector
    tag: pgvector
    version: pg17
    dockerfile: |
      FROM pgvector/pgvector:pg17

  minio:
    platforms: [linux/amd64, linux/arm64]
    context: images/minio
    tag: minio
    version: RELEASE.2025-05-24T17-08-30Z
    dockerfile: |
      FROM minio/minio:RELEASE.2025-05-24T17-08-30Z

  miniomc:
    platforms: [linux/amd64, linux/arm64]
    context: images/miniomc
    tag: minio-mc
    version: latest
    dockerfile: |
      FROM minio/mc:latest

  memgraphmage:
    platforms: [linux/amd64, linux/arm64]
    context: images/memgraphmage
    tag: memgraph-mage
    version: 3.2.1
    dockerfile: |
      FROM memgraph/memgraph-mage:3.2.1

  ollama:
    platforms: [linux/amd64, linux/arm64]
    context: images/ollama
    tag: ollama
    version: 0.9.1
    dockerfile: |
      FROM ollama/ollama:0.9.1

  weaviate:
    platforms: [linux/amd64, linux/arm64]
    context: images/weaviate
    tag: weaviate
    version: 1.30.1
    dockerfile: |
      FROM semitechnologies/weaviate:1.30.1

  neo4j:
    platforms: [linux/amd64, linux/arm64]
    context: images/neo4j
    tag: neo4j
    version: 5.26.5-community-ubi9
    dockerfile: |
      FROM neo4j:5.26.5-community-ubi9
