images:
  alpine:
    base: alpine:3.21
    platforms: [linux/amd64, linux/arm64]
    context: images/alpine
    tag: alpine
    version: 3.21
    dockerfile: |
      FROM alpine:3.21

  goappbuilder:
    base: golang:1.23.8-alpine3.21
    platforms: [linux/amd64, linux/arm64]
    context: images/goappbuilder
    tag: goapp-builder
    version: 1.23.8-alpine3.21
    dockerfile: |
      FROM golang:1.23.8-alpine3.21

  ray:
    base: rayproject/ray:2.44.1-py311-numpy2x
    platforms: [linux/amd64]
    context: images/ray
    tag: ray
    version: 2.44.1-py311-numpy2x
    dockerfile: |
      FROM rayproject/ray:2.44.1-py311-numpy2x

  rayaarch64:
    base: rayproject/ray:2.44.1-py311-numpy2x
    platforms: [linux/arm64]
    context: images/ray
    tag: ray
    version: 2.44.1-py311-numpy2x-aarch64
    dockerfile: |
      FROM rayproject/ray:2.44.1-py311-numpy2x

  node:
    base: node:24-alpine3.21
    platforms: [linux/amd64, linux/arm64]
    context: images/node
    tag: node
    version: 24-alpine3.21
    dockerfile: |
      FROM node:24-alpine3.21

  nginx:
    base: nginx:1.27-alpine3.21
    platforms: [linux/amd64, linux/arm64]
    context: images/nginx
    tag: nginx
    version: 1.27-alpine3.21
    dockerfile: |
      FROM nginx:1.27-alpine3.21

  redis:
    base: docker.io/redis:8-alpine3.21
    platforms: [linux/amd64, linux/arm64]
    context: images/redis
    tag: redis
    version: 8-alpine3.21
    dockerfile: |
      FROM docker.io/redis:8-alpine3.21

  postgres:
    base: docker.io/postgres:17.5-alpine3.21 
    platforms: [linux/amd64, linux/arm64]
    context: images/postgres
    tag: postgres
    version: 17.5-alpine3.21
    dockerfile: |
      FROM docker.io/postgres:17.5-alpine3.21

  minio:
    base: minio/minio:RELEASE.2025-05-24T17-08-30Z
    platforms: [linux/amd64, linux/arm64]
    context: images/minio
    tag: minio
    version: RELEASE.2025-05-24T17-08-30Z
    dockerfile: |
      FROM minio/minio:RELEASE.2025-05-24T17-08-30Z