platforms: [linux/amd64, linux/arm64]
context: images/alpine
tag: alpine
versions:
  "3.21":
    dockerfile: |
      FROM alpine:3.21
  "3.22":
    dockerfile: |
      FROM alpine:3.22
  "3.23":
    dockerfile: |
      FROM alpine:3.23
