name: Build DevContainer Image

on:
  push:
    branches:
      - main

permissions:
  contents: read
  packages: write

jobs:
  filter-changes:
    runs-on: ubuntu-latest
    outputs:
      devcbase: ${{ steps.filter.outputs.devcbase }}
      devc: ${{ steps.filter.outputs.devc }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Filter changed paths
        id: filter
        uses: dorny/paths-filter@v3
        with:
          filters: |
            devcbase:
              - 'devcontainer/Dockerfile-base'
            devc:
              - 'devcontainer/Dockerfile'

  build-and-push:
    needs: filter-changes
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        component:
          - name: devcbase
            path: devcontainer/Dockerfile-base
            context: devcontainer
            tag: devcontainer
            version: ubuntu2404-base
            platforms: linux/amd64,linux/arm64
            condition: ${{ needs.filter-changes.outputs.devcbase }}
          - name: devc
            path: devcontainer/Dockerfile
            context: devcontainer
            tag: devcontainer
            version: ubuntu2404
            platforms: linux/amd64,linux/arm64
            condition: ${{ needs.filter-changes.outputs.devc }}
    steps:
      - name: Check if component has changes
        if: ${{ matrix.component.condition != 'true' }}
        run: |
          echo "No changes detected for ${{ matrix.component.name }}. Skipping build."
          exit 0

      - name: Checkout code
        if: ${{ matrix.component.condition == 'true' }}
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        if: ${{ matrix.component.condition == 'true' }}
        uses: docker/setup-buildx-action@v3

      - name: Log in to Aliyuncs Registry
        if: ${{ matrix.component.condition == 'true' }}
        uses: docker/login-action@v3
        with:
          registry: registry.cn-hangzhou.aliyuncs.com
          username: ${{ secrets.ALIYUNCS_USERNAME }}
          password: ${{ secrets.ALIYUNCS_TOKEN }}

      - name: Build and push ${{ matrix.component.name }} image
        if: ${{ matrix.component.condition == 'true' }}
        uses: docker/build-push-action@v5
        with:
          context: ${{ matrix.component.context }}
          file: ${{ matrix.component.path }}
          push: true
          platforms: ${{ matrix.component.platforms }}
          cache-from: type=gha,scope=${{ matrix.component.name }}
          cache-to: type=gha,mode=max,scope=${{ matrix.component.name }}
          tags: |
            registry.cn-hangzhou.aliyuncs.com/lacogito/${{ matrix.component.tag }}:${{ matrix.component.version }}