name: Build DevContainer Image

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      # Check out the repository code
      - name: Checkout code
        uses: actions/checkout@v4

      # Set up Docker Buildx (for multi-platform builds, if needed)
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Aliyuncs Registry
        uses: docker/login-action@v3
        with:
          registry: registry.cn-hangzhou.aliyuncs.com
          username: ${{ secrets.ALIYUNCS_USERNAME }}
          password: ${{ secrets.ALIYUNCS_TOKEN }}

      - name: Check devcontainer changes
        uses: dorny/paths-filter@v3
        id: devcontainer-changes
        with:
          filters: |
            devcontainer:
              - 'devcontainer/Dockerfile'

      # Build and push Docker image
      - name: Build and push devcontainer image
        if: steps.devcontainer-changes.outputs.matched
        uses: docker/build-push-action@v5
        with:
          context: .
          file: devcontainer/Dockerfile
          push: true
          platforms: linux/amd64,linux/arm64
          cache-from: type=gha
          cache-to: type=gha,mode=max
          tags: |
            registry.cn-hangzhou.aliyuncs.com/lacogito/devcontainer:ubuntu2404
